### ISSUE TITLE
Error trying demo

### ISSUE THREAD

**Issue by genesy** [hiitiger/gelectron#30]
```
projects\gelectron\electron-overlay\build\electron_overlay.vcxproj(50,945): error MSB4025: The project file could not be loaded. '', hexadecim
al value 0x0C, is an invalid character. Line 50, position 945.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\projects\gelectron\electron-overlay
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-overlay@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

using visual studio 2019.

**Comment by daMichl** [comment]
check the other similar issue:
https://github.com/hiitiger/gelectron/issues/28#issuecomment-578369385
