### ISSUE TITLE
Another Build Error

### ISSUE THREAD

**Issue by GRhin** [hiitiger/gelectron#32]
Hi, I realise there are other issues with the same name, but they contain different errors.
I managed to follow the front page instructions to set up demo, untill i got to "npm run compile:electron"
Python 3.8 is installed and running, as is vistual studio 2017, as required for previous steps.
The console error is as follows (seems to repeat 3 times)
```
> gelectron@1.0.0 compile:electron C:\Users\GRhin\coding\gelectron-master\client
> electron-rebuild -v 2.0.8

× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\cygwin64\bin\python3.8.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\GRhin\\coding\\gelectron-master\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\GRhin\coding\gelectron-master\electron-overlay
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\cygwin64\bin\python3.8.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\GRhin\\coding\\gelectron-master\\client\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.8" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\GRhin\coding\gelectron-master\electron-overlay
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\Users\GRhin\coding\gelectron-master\client\node_modules\spawn-rx\node_modules\rxjs\Subscriber.js:191:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the gelectron@1.0.0 compile:electron script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GRhin\AppData\Roaming\npm-cache\_logs\2020-04-02T04_39_35_686Z-debug.log

× Rebuild Failed
```

The error log says:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile:electron'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'precompile:electron', 'compile:electron', 'postcompile:electron' ]
5 info lifecycle gelectron@1.0.0~precompile:electron: gelectron@1.0.0
6 info lifecycle gelectron@1.0.0~compile:electron: gelectron@1.0.0
7 verbose lifecycle gelectron@1.0.0~compile:electron: unsafe-perm in lifecycle true
8 verbose lifecycle gelectron@1.0.0~compile:electron: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\GRhin\coding\gelectron-master\client\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\cygwin64\bin;C:\Users\GRhin\AppData\Local\Programs\Python\Python38-32;C:\Users\GRhin\AppData\Roaming\npm;C:\Users\GRhin\AppData\Local\atom\bin;C:\Users\GRhin\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle gelectron@1.0.0~compile:electron: CWD: C:\Users\GRhin\coding\gelectron-master\client
10 silly lifecycle gelectron@1.0.0~compile:electron: Args: [ '/d /s /c', 'electron-rebuild -v 2.0.8' ]
11 silly lifecycle gelectron@1.0.0~compile:electron: Returned: code: 4294967295  signal: null
12 info lifecycle gelectron@1.0.0~compile:electron: Failed to exec compile:electron script
13 verbose stack Error: gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid gelectron@1.0.0
15 verbose cwd C:\Users\GRhin\coding\gelectron-master\client
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:electron"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 4294967295
22 error gelectron@1.0.0 compile:electron: `electron-rebuild -v 2.0.8`
22 error Exit status 4294967295
23 error Failed at the gelectron@1.0.0 compile:electron script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]
```
What have I missed?

**Comment by GRhin** [comment]
installing an older version of python fixed it
